INSERT INTO bitbucket_repositories (repo_id, repo_name, repo_slug, clone_url_ssh, status, comment, updated_on) VALUES
('flask', 'Flask', 'flask', 'ssh://git@github.com/pallets/flask.git', 'NEW', 'Lightweight Python web framework', '2024-12-29 13:00:00'),
('pytest', 'Pytest', 'pytest', 'ssh://git@github.com/pytest-dev/pytest.git', 'NEW', 'Testing framework for Python', '2024-12-29 13:10:00'),
('terraform-modules', 'Terraform Modules', 'terraform-modules', 'ssh://git@github.com/terraform-aws-modules/terraform-aws-vpc.git', 'NEW', 'Terraform modules and examples', '2024-12-29 13:20:00'),
('docker-learn', 'Docker Learn', 'docker-learn', 'ssh://git@github.com/docker/labs.git', 'NEW', 'Example Dockerfiles for learning', '2024-12-29 13:30:00'),
('rustlings', 'Rustlings', 'rustlings', 'ssh://git@github.com/rust-lang/rustlings.git', 'NEW', 'Small exercises to learn Rust', '2024-12-29 13:40:00'),
('cpp-starter', 'C++ Starter', 'cpp-starter', 'ssh://git@github.com/TheAlgorithms/C-Plus-Plus.git', 'NEW', 'Starter project for C++', '2024-12-29 13:50:00'),
('minimal-mistakes', 'Minimal Mistakes', 'minimal-mistakes', 'ssh://git@github.com/mmistakes/minimal-mistakes.git', 'NEW', 'Simple Jekyll theme for static sites', '2024-12-29 14:00:00'),
('maven-archetype', 'Maven Archetype', 'maven-archetype', 'ssh://git@github.com/apache/maven-archetype.git', 'NEW', 'Maven example project', '2024-12-29 14:10:00'),
('json-server', 'JSON Server', 'json-server', 'ssh://git@github.com/typicode/json-server.git', 'NEW', 'Mock REST APIs with JSON', '2024-12-29 14:20:00'),
('go-by-example', 'Go By Example', 'go-by-example', 'ssh://git@github.com/mmcgrana/gobyexample.git', 'NEW', 'Hands-on code examples for learning Go', '2024-12-29 14:30:00'),
('gitignore', 'Gitignore', 'gitignore', 'ssh://git@github.com/github/gitignore.git', 'NEW', 'Collection of useful .gitignore templates', '2024-12-29 14:40:00'),
('jekyll', 'Jekyll', 'jekyll', 'ssh://git@github.com/jekyll/jekyll.git', 'NEW', 'Static site generator', '2024-12-29 14:50:00'),
('bootstrap', 'Bootstrap', 'bootstrap', 'ssh://git@github.com/twbs/bootstrap.git', 'NEW', 'Frontend framework', '2024-12-29 15:00:00'),
('moment', 'Moment.js', 'moment', 'ssh://git@github.com/moment/moment.git', 'NEW', 'Date and time parsing library', '2024-12-29 15:10:00'),
('chartjs', 'Charts.js', 'chartjs', 'ssh://git@github.com/chartjs/Chart.js.git', 'NEW', 'Simple yet flexible charting library', '2024-12-29 15:20:00'),
('ansible-examples', 'Ansible Examples', 'ansible-examples', 'ssh://git@github.com/ansible/ansible-examples.git', 'NEW', 'Example playbooks for Ansible', '2024-12-29 15:30:00'),
('express', 'Express.js', 'express', 'ssh://git@github.com/expressjs/express.git', 'NEW', 'Fast, unopinionated web framework for Node.js', '2024-12-29 15:40:00'),
('spring-boot-examples', 'Spring Boot Examples', 'spring-boot-examples', 'ssh://git@github.com:gothinkster/spring-boot-realworld-example-app.git', 'NEW', 'Sample projects using Spring Boot', '2024-12-29 15:50:00');
