INSERT INTO bitbucket_repositories (repo_id, repo_name, repo_slug, clone_url_ssh, status, comment, updated_on) VALUES
('flask', 'Flask', 'flask', 'ssh://git@github.com/pallets/flask.git', 'NEW', 'Lightweight Python web framework', '2024-12-29 13:00:00'),
('pytest', 'Pytest', 'pytest', 'ssh://git@github.com/pytest-dev/pytest.git', 'NEW', 'Testing framework for Python', '2024-12-29 13:10:00'),
('django', 'Django', 'django', 'ssh://git@github.com/django/django.git', 'NEW', 'High-level Python web framework', '2024-12-29 13:20:00'),
('fastapi', 'FastAPI', 'fastapi', 'ssh://git@github.com/tiangolo/fastapi.git', 'NEW', 'Modern Python web framework', '2024-12-29 13:30:00'),
('requests', 'Requests', 'requests', 'ssh://git@github.com/psf/requests.git', 'NEW', 'Simple HTTP library for Python', '2024-12-29 13:40:00'),
('scrapy', 'Scrapy', 'scrapy', 'ssh://git@github.com/scrapy/scrapy.git', 'NEW', 'Web scraping framework', '2024-12-29 13:50:00'),
('pandas', 'Pandas', 'pandas', 'ssh://git@github.com/pandas-dev/pandas.git', 'NEW', 'Data analysis library', '2024-12-29 14:00:00'),
('scikit-learn', 'Scikit-learn', 'scikit-learn', 'ssh://git@github.com/scikit-learn/scikit-learn.git', 'NEW', 'Machine learning library', '2024-12-29 14:10:00'),
('click', 'Click', 'click', 'ssh://git@github.com/pallets/click.git', 'NEW', 'Command-line interface toolkit', '2024-12-29 14:20:00'),
('celery', 'Celery', 'celery', 'ssh://git@github.com/celery/celery.git', 'NEW', 'Distributed task queue', '2024-12-29 14:30:00'),
('react', 'React', 'react', 'ssh://git@github.com/facebook/react.git', 'NEW', 'JavaScript library for UI', '2024-12-29 14:40:00'),
('vue', 'Vue.js', 'vue', 'ssh://git@github.com/vuejs/vue.git', 'NEW', 'JavaScript framework for UI', '2024-12-29 14:50:00'),
('express', 'Express.js', 'express', 'ssh://git@github.com/expressjs/express.git', 'NEW', 'Web framework for Node.js', '2024-12-29 15:00:00'),
('nextjs', 'Next.js', 'nextjs', 'ssh://git@github.com/vercel/next.js.git', 'NEW', 'React-based framework', '2024-12-29 15:10:00'),
('electron', 'Electron', 'electron', 'ssh://git@github.com/electron/electron.git', 'NEW', 'Desktop app framework', '2024-12-29 15:20:00'),
('lodash', 'Lodash', 'lodash', 'ssh://git@github.com/lodash/lodash.git', 'NEW', 'JavaScript utility library', '2024-12-29 15:30:00'),
('moment', 'Moment.js', 'moment', 'ssh://git@github.com/moment/moment.git', 'NEW', 'Date/time library', '2024-12-29 15:40:00'),
('chartjs', 'Chart.js', 'chartjs', 'ssh://git@github.com/chartjs/Chart.js.git', 'NEW', 'Charting library for JavaScript', '2024-12-29 15:50:00'),
('threejs', 'Three.js', 'threejs', 'ssh://git@github.com/mrdoob/three.js.git', 'NEW', '3D graphics library', '2024-12-29 16:00:00'),
('npm-cli', 'NPM CLI', 'npm-cli', 'ssh://git@github.com/npm/cli.git', 'NEW', 'NPM command-line interface', '2024-12-29 16:10:00'),
('junit5', 'JUnit5', 'junit5', 'ssh://git@github.com/junit-team/junit5.git', 'NEW', 'Java testing framework', '2024-12-29 16:20:00'),
('maven-archetype', 'Maven Archetype', 'maven-archetype', 'ssh://git@github.com/apache/maven-archetype.git', 'NEW', 'Maven example project', '2024-12-29 16:30:00'),
('spring-boot', 'Spring Boot', 'spring-boot', 'ssh://git@github.com/spring-projects/spring-boot.git', 'NEW', 'Spring Boot framework', '2024-12-29 16:40:00'),
('terraform-modules', 'Terraform Modules', 'terraform-modules', 'ssh://git@github.com/terraform-aws-modules/terraform-aws-vpc.git', 'NEW', 'Terraform modules and examples', '2024-12-29 16:50:00'),
('ansible-examples', 'Ansible Examples', 'ansible-examples', 'ssh://git@github.com/ansible/ansible-examples.git', 'NEW', 'Example playbooks for Ansible', '2024-12-29 17:00:00'),
('rustlings', 'Rustlings', 'rustlings', 'ssh://git@github.com/rust-lang/rustlings.git', 'NEW', 'Small exercises to learn Rust', '2024-12-29 17:10:00'),
('cpp-starter', 'C++ Starter', 'cpp-starter', 'ssh://git@github.com/TheAlgorithms/C-Plus-Plus.git', 'NEW', 'Starter project for C++', '2024-12-29 17:20:00'),
('bootstrap', 'Bootstrap', 'bootstrap', 'ssh://git@github.com/twbs/bootstrap.git', 'NEW', 'Frontend CSS framework', '2024-12-29 17:30:00'),
('jekyll', 'Jekyll', 'jekyll', 'ssh://git@github.com/jekyll/jekyll.git', 'NEW', 'Static site generator', '2024-12-29 17:40:00'),
('dotnet-runtime', 'DotNet Runtime', 'dotnet-runtime', 'ssh://git@github.com/dotnet/runtime.git', 'NEW', '.NET runtime implementation', '2024-12-29 17:50:00');
('docker-learn', 'Docker Learn', 'docker-learn', 'ssh://git@github.com/docker/labs.git', 'NEW', 'Example Dockerfiles for learning', '2024-12-29 13:30:00'),
('minimal-mistakes', 'Minimal Mistakes', 'minimal-mistakes', 'ssh://git@github.com/mmistakes/minimal-mistakes.git', 'NEW', 'Simple Jekyll theme for static sites', '2024-12-29 14:00:00'),
('json-server', 'JSON Server', 'json-server', 'ssh://git@github.com/typicode/json-server.git', 'NEW', 'Mock REST APIs with JSON', '2024-12-29 14:20:00'),
('go-by-example', 'Go By Example', 'go-by-example', 'ssh://git@github.com/mmcgrana/gobyexample.git', 'NEW', 'Hands-on code examples for learning Go', '2024-12-29 14:30:00'),
('gitignore', 'Gitignore', 'gitignore', 'ssh://git@github.com/github/gitignore.git', 'NEW', 'Collection of useful .gitignore templates', '2024-12-29 14:40:00'),
('spring-boot-examples', 'Spring Boot Examples', 'spring-boot-examples', 'ssh://git@github.com:gothinkster/spring-boot-realworld-example-app.git', 'NEW', 'Sample projects using Spring Boot', '2024-12-29 15:50:00');
