services:
  postgres:
    build:
      context: .
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    container_name: postgres13e
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/pgsql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
