services:
  airflow:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GLOBAL_CERT: ${GLOBAL_CERT}
        GLOBAL_INDEX: ${GLOBAL_INDEX}
        GLOBAL_INDEX_URL: ${GLOBAL_INDEX_URL}
    env_file:
      - .env  # Shared environment file
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      # Use the IP or hostname of the PostgreSQL server
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@<POSTGRES_HOST>:<POSTGRES_HOST_PORT>/${POSTGRES_DB}
    volumes:
      - ./cloned_repositories:/mnt/cloned_repositories
      - ${SSH_KEYS_PATH:-~/.ssh/id_rsa}:/root/.ssh/id_rsa:ro
      - ${SSH_KEYS_PUB_PATH:-~/.ssh/id_rsa.pub}:/root/.ssh/id_rsa.pub:ro
      - ${CERT_PATH:-/dev/null}:/etc/pip/certs/self-signed-cert.pem:ro
    ports:
      - "${AIRFLOW_HOST_PORT:-8088}:8080"  # Expose Airflow on its host machine