services:
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile-airflow
      args:
        GLOBAL_CERT: ${GLOBAL_CERT}
        GLOBAL_INDEX: ${GLOBAL_INDEX}
        GLOBAL_INDEX_URL: ${GLOBAL_INDEX_URL}
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    container_name: airflow-webserver
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
      RULESET_MAPPING_FILE: ${RULESET_MAPPING_FILE}
      METRICS_DATABASE_USER: ${METRICS_DATABASE_USER}
      METRICS_DATABASE_PASSWORD: ${METRICS_DATABASE_PASSWORD}
      METRICS_DATABASE_HOST: ${METRICS_DATABASE_HOST}
      METRICS_DATABASE_PORT: ${METRICS_DATABASE_PORT}
      METRICS_DATABASE_NAME: ${METRICS_DATABASE_NAME}
      CLONED_REPOSITORIES_DIR: ${CLONED_REPOSITORIES_DIR}
      TRIVYIGNORE_TEMPLATE: ${TRIVYIGNORE_TEMPLATE}
      SYFT_CONFIG_PATH: ${SYFT_CONFIG_PATH}
      GRYPE_CONFIG_PATH: ${GRYPE_CONFIG_PATH}
      SEMGREP_CONFIG_DIR: ${SEMGREP_CONFIG_DIR}

      KANTRA_RULESET_FILE: ${KANTRA_RULESET_FILE}
      KANTRA_OUTPUT_ROOT: ${KANTRA_OUTPUT_ROOT}

    volumes:
      - ./cloned_repositories:/home/airflow/cloned_repositories
      - ${KANTRA_OUTPUT_ROOT:-./tmp}:/home/airflow/output
      - ${SSH_KEYS_PATH:-~/.ssh/porfolios_github_key}:/home/airflow/.ssh/id_rsa:ro
      - ${SSH_KEYS_PUB_PATH:-~/.ssh/porfolios_github_key.pub}:/home/airflow/.ssh/id_rsa.pub:ro
      - ${CERT_PATH:-/dev/null}:/etc/pip/certs/self-signed-cert.pem:ro
    ports:
      - "8088:8080"  # Map host port 8088 to container port 8080
    restart: always

networks:
  default:
    name: airflow_network
