services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
      args:
        USER_ID: ${HOST_UID}
        GROUP_ID: ${HOST_GID}
    container_name: postgres13e
    ports:
      - "5422:5432"
    volumes:
      - ./pgdata1:/var/lib/pgsql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
