services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - ${ENV_FILE:-.env} # Default to .env if ENV_FILE is not set
    ports:
      - "5433:5432"
    volumes:
      - ./tools/postgresql/data:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    secrets:
      - ssh_key
      - ssh_key_pub
      - self_signed_cert
    env_file:
      - ${ENV_FILE:-.env} # Default to .env if ENV_FILE is not set
    depends_on:
      - postgres
    ports:
      - "8088:8080"
    volumes:
      - ./cloned_repositories:/mnt/cloned_repositories

secrets:
  ssh_key:
    external: true
  ssh_key_pub:
    external: true
  self_signed_cert:
    external: true
