version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GLOBAL_CERT: ${GLOBAL_CERT}
        GLOBAL_INDEX: ${GLOBAL_INDEX}
        GLOBAL_INDEX_URL: ${GLOBAL_INDEX_URL}
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    env_file:
      - .env
    environment:
      # Proxy settings
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY},${POSTGRES_HOST}
      # Airflow specific environment variables are already defined in .env
    volumes:
      - ./cloned_repositories:/mnt/cloned_repositories
      - ${SSH_KEYS_PATH:-~/.ssh/id_rsa}:/home/airflow/.ssh/id_rsa:ro
      - ${SSH_KEYS_PUB_PATH:-~/.ssh/id_rsa.pub}:/home/airflow/.ssh/id_rsa.pub:ro
      - ${CERT_PATH:-/dev/null}:/etc/pip/certs/self-signed-cert.pem:ro
      - ./dags:/home/airflow/airflow/dags
      - ./modular:/home/airflow/airflow/dags/modular
      - ./logs:/home/airflow/airflow/logs
      - ./plugins:/home/airflow/airflow/plugins
      # Mounting tools if needed
      - ./tools:/usr/local/bin
    ports:
      - "${AIRFLOW_HOST_PORT:-8088}:8088"
    networks:
      - airflow_network
    restart: always
    # No need to specify user here since Dockerfile sets the USER

networks:
  airflow_network:
    driver: bridge

# No volumes section needed since PostgreSQL is external
