version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./tools/postgresql/data:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - postgres
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    volumes:
      - ./cloned_repositories:/mnt/cloned_repositories
      - ${SSH_KEYS_PATH:+${SSH_KEYS_PATH}/ssh_key:/root/.ssh/id_rsa:ro}
      - ${SSH_KEYS_PATH:+${SSH_KEYS_PATH}/ssh_key_pub:/root/.ssh/id_rsa.pub:ro}
      - ${CERT_PATH:+${CERT_PATH}:/etc/pip/certs/self-signed-cert.pem:ro}
    ports:
      - "8088:8080"
