FROM almalinux:8

# Set environment variables
ENV POSTGRES_VERSION=13
ENV PGDATA=/var/lib/pgsql/data
ENV PGSOCKET=/tmp  # Set socket directory to /tmp to avoid permission issues

# Accept UID and GID as build arguments
ARG USER_ID=1000
ARG GROUP_ID=1000

# Install PostgreSQL
RUN dnf -y update && \
    dnf -y install dnf-plugins-core && \
    dnf -y module enable postgresql:${POSTGRES_VERSION} && \
    dnf -y install postgresql-server postgresql-contrib && \
    dnf clean all

# Create the 'postgres' group if it doesn't exist
RUN if ! getent group postgres >/dev/null; then \
        groupadd -g ${GROUP_ID} postgres; \
    fi

# Create the 'postgres' user if it doesn't exist
RUN if ! id -u postgres >/dev/null 2>&1; then \
        useradd -u ${USER_ID} -g postgres -m postgres; \
    fi

# Prepare the directory structure
RUN mkdir -p /var/lib/pgsql && \
    mkdir -p "${PGDATA}" && \
    # Do NOT create "${PGDATA}/log" here to keep PGDATA empty for initdb
    chown -R postgres:postgres /var/lib/pgsql && \
    chmod 700 "${PGDATA}"

# Copy the entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Expose PostgreSQL port
EXPOSE 5432

# Switch to the 'postgres' user for runtime
USER postgres

# Set the entrypoint and command
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["postgres", "-D", "/var/lib/pgsql/data", "-k", "/tmp"]
