services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GLOBAL_CERT: ${GLOBAL_CERT}
        GLOBAL_INDEX: ${GLOBAL_INDEX}
        GLOBAL_INDEX_URL: ${GLOBAL_INDEX_URL}
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    env_file:
      - .env-local  # Use the appropriate .env file
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: "${NO_PROXY:-localhost},${POSTGRES_HOST}"
    volumes:
      - ./cloned_repositories:/mnt/cloned_repositories
      - ./dags:/home/airflow/airflow/dags
      - ./logs:/home/airflow/airflow/logs
      - ./plugins:/home/airflow/airflow/plugins
    ports:
      - "8088:8080"  # Map host port 8088 to container port 8080
    networks:
      - airflow_network
    restart: always

networks:
  airflow_network:
    driver: bridge