rules:
  # 1) Log4j 1.x
  - ruleID: logging-0100-log4j1
    description: "Detected Apache Log4j 1.x usage"
    category: "logging"
    effort: 1
    message: "Application uses Log4j 1.x which is deprecated. Consider upgrading to Log4j 2 or using SLF4J."
    labels:
      - "cto.io/logging=Log4j1"
    tags:
      - "Logging=Log4j1"
    when:
      - or:
          - builtin.java:
              reference:
                location: IMPORT
                pattern: "org\\.apache\\.log4j\\..*"
          - builtin.filecontent:
              filePattern: "pom.xml"
              pattern: "<groupId>log4j</groupId>\\s*<artifactId>log4j</artifactId>"
          - builtin.filecontent:
              filePattern: "build.gradle"
              pattern: "implementation\\s*['\"]log4j:log4j"

  # 2) Log4j 2
  - ruleID: logging-0200-log4j2
    description: "Detected Apache Log4j 2 usage"
    category: "logging"
    effort: 1
    message: "Application uses Log4j 2 which is a modern logging framework."
    labels:
      - "cto.io/logging=Log4j2"
    tags:
      - "Logging=Log4j2"
    when:
      - or:
          - builtin.java:
              reference:
                location: IMPORT
                pattern: "org\\.apache\\.logging\\.log4j\\..*"
          - builtin.filecontent:
              filePattern: "pom.xml"
              pattern: "<groupId>org\\.apache\\.logging\\.log4j</groupId>"
          - builtin.filecontent:
              filePattern: "build.gradle"
              pattern: "implementation\\s*['\"]org.apache.logging.log4j"

  # 3) SLF4J
  - ruleID: logging-0300-slf4j
    description: "Detected SLF4J usage"
    category: "logging"
    effort: 1
    message: "Application uses SLF4J which is a logging facade."
    labels:
      - "cto.io/logging=SLF4J"
    tags:
      - "Logging=SLF4J"
    when:
      - or:
          - builtin.java:
              reference:
                location: IMPORT
                pattern: "org\\.slf4j\\..*"
          - builtin.filecontent:
              filePattern: "pom.xml"
              pattern: "<groupId>org\\.slf4j</groupId>"
          - builtin.filecontent:
              filePattern: "build.gradle"
              pattern: "implementation\\s*['\"]org.slf4j"

  # 4) Logback
  - ruleID: logging-0400-logback
    description: "Detected Logback usage"
    category: "logging"
    effort: 1
    message: "Application uses Logback which is the native implementation of SLF4J."
    labels:
      - "cto.io/logging=Logback"
    tags:
      - "Logging=Logback"
    when:
      - or:
          - builtin.java:
              reference:
                location: IMPORT
                pattern: "ch\\.qos\\.logback\\..*"
          - builtin.filecontent:
              filePattern: "pom.xml"
              pattern: "<groupId>ch\\.qos\\.logback</groupId>"
          - builtin.filecontent:
              filePattern: "build.gradle"
              pattern: "implementation\\s*['\"]ch.qos.logback"

  # 5) Apache Commons Logging
  - ruleID: logging-0500-commons-logging
    description: "Detected Apache Commons Logging usage"
    category: "logging"
    effort: 1
    message: "Application uses Commons Logging. Consider migrating to SLF4J."
    labels:
      - "cto.io/logging=CommonsLogging"
    tags:
      - "Logging=CommonsLogging"
    when:
      - or:
          - builtin.java:
              reference:
                location: IMPORT
                pattern: "org\\.apache\\.commons\\.logging\\..*"
          - builtin.filecontent:
              filePattern: "pom.xml"
              pattern: "<groupId>commons-logging</groupId>"
          - builtin.filecontent:
              filePattern: "build.gradle"
              pattern: "implementation\\s*['\"]commons-logging"

  # 6) JBoss Logging
  - ruleID: logging-0600-jbosslogging
    description: "Detected JBoss Logging usage"
    category: "logging"
    effort: 1
    message: "Application uses JBoss Logging. Consider standardizing on SLF4J."
    labels:
      - "cto.io/logging=JBossLogging"
    tags:
      - "Logging=JBossLogging"
    when:
      - or:
          - builtin.java:
              reference:
                location: IMPORT
                pattern: "org\\.jboss\\.logging\\..*"
          - builtin.filecontent:
              filePattern: "pom.xml"
              pattern: "<groupId>org\\.jboss\\.logging</groupId>"
          - builtin.filecontent:
              filePattern: "build.gradle"
              pattern: "implementation\\s*['\"]org.jboss.logging"

  # 7) Java Util Logging (JUL)
  - ruleID: logging-0700-javautil
    description: "Detected Java Util Logging usage"
    category: "logging"
    effort: 1
    message: "Application uses Java Util Logging. Consider using a more modern logging framework."
    labels:
      - "cto.io/logging=JavaUtil"
    tags:
      - "Logging=JavaUtil"
    when:
      - or:
          - builtin.java:
              reference:
                location: IMPORT
                pattern: "java\\.util\\.logging\\..*"
