- ruleID: "appserver-tomcat-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=Tomcat"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: org\.apache\.tomcat:.*
  message: "Detected usage of Tomcat application server."
  description: "Detected usage of Tomcat application server."

- ruleID: "appserver-jetty-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=Jetty"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: org\.eclipse\.jetty:.*
  message: "Detected usage of Jetty application server."
  description: "Detected usage of Jetty application server."

- ruleID: "appserver-wildfly-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=WildFly"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: org\.wildfly:.*
  message: "Detected usage of WildFly application server."
  description: "Detected usage of WildFly application server."

- ruleID: "appserver-jboss-eap-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=JBossEAP"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: org\.jboss\.eap:.*
  message: "Detected usage of JBoss EAP application server."
  description: "Detected usage of JBoss EAP application server."

- ruleID: "appserver-weblogic-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=WebLogic"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: com\.oracle\.weblogic:.*
  message: "Detected usage of WebLogic application server."
  description: "Detected usage of WebLogic application server."

- ruleID: "appserver-websphere-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=WebSphere"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: com\.ibm\.websphere:.*
  message: "Detected usage of WebSphere application server."
  description: "Detected usage of WebSphere application server."

- ruleID: "appserver-glassfish-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=GlassFish"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: org\.glassfish:.*
  message: "Detected usage of GlassFish application server."
  description: "Detected usage of GlassFish application server."

- ruleID: "appserver-payara-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=Payara"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: fish\.payara\..*:.*
  message: "Detected usage of Payara application server."
  description: "Detected usage of Payara application server."

- ruleID: "appserver-undertow-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=Undertow"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: io\.undertow:.*
  message: "Detected usage of Undertow application server."
  description: "Detected usage of Undertow application server."
