- ruleID: "appserver-tomcat-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=Tomcat"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: org\.apache\.tomcat:.*
      - builtin.filecontent:
          filePattern: build.gradle
          pattern: implementation\s*['"]org.apache.tomcat:.*['"]
      - builtin.filecontent:
          filePattern: build.gradle.kts
          pattern: implementation\(['"]org.apache.tomcat:.*['"]\)
      - builtin.filecontent:
          filePattern: build.gradle
          pattern: appServer\s*['"]org.apache.tomcat:.*['"]
      - builtin.filecontent:
          filePattern: gradle.properties
          pattern: tomcatVersion\s*=\s*\d+\.\d+\.\d+
  message: "Detected usage of Tomcat application server."
  description: "Detected usage of Tomcat application server."

- ruleID: "appserver-jetty-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=Jetty"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: org\.eclipse\.jetty:.*
      - builtin.filecontent:
          filePattern: build.gradle
          pattern: implementation\s*['"]org.eclipse.jetty:.*['"]
      - builtin.filecontent:
          filePattern: build.gradle.kts
          pattern: implementation\(['"]org.eclipse.jetty:.*['"]\)
      - builtin.filecontent:
          filePattern: gradle.properties
          pattern: jettyVersion\s*=\s*\d+\.\d+\.\d+
  message: "Detected usage of Jetty application server."
  description: "Detected usage of Jetty application server."

- ruleID: "appserver-wildfly-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=WildFly"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: org\.wildfly:.*
      - builtin.filecontent:
          filePattern: build.gradle
          pattern: implementation\s*['"]org.wildfly:.*['"]
      - builtin.filecontent:
          filePattern: build.gradle.kts
          pattern: implementation\(['"]org.wildfly:.*['"]\)
      - builtin.filecontent:
          filePattern: gradle.properties
          pattern: wildflyVersion\s*=\s*\d+\.\d+\.\d+
  message: "Detected usage of WildFly application server."
  description: "Detected usage of WildFly application server."

- ruleID: "appserver-jboss-eap-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=JBossEAP"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: org\.jboss\.eap:.*
      - builtin.filecontent:
          filePattern: build.gradle
          pattern: implementation\s*['"]org.jboss.eap:.*['"]
      - builtin.filecontent:
          filePattern: build.gradle.kts
          pattern: implementation\(['"]org.jboss.eap:.*['"]\)
  message: "Detected usage of JBoss EAP application server."
  description: "Detected usage of JBoss EAP application server."

- ruleID: "appserver-weblogic-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=WebLogic"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: com\.oracle\.weblogic:.*
      - builtin.filecontent:
          filePattern: build.gradle
          pattern: implementation\s*['"]com.oracle.weblogic:.*['"]
      - builtin.filecontent:
          filePattern: build.gradle.kts
          pattern: implementation\(['"]com.oracle.weblogic:.*['"]\)
  message: "Detected usage of WebLogic application server."
  description: "Detected usage of WebLogic application server."

- ruleID: "appserver-websphere-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=WebSphere"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: com\.ibm\.websphere:.*
      - builtin.filecontent:
          filePattern: build.gradle
          pattern: implementation\s*['"]com.ibm.websphere:.*['"]
      - builtin.filecontent:
          filePattern: build.gradle.kts
          pattern: implementation\(['"]com.ibm.websphere:.*['"]\)
  message: "Detected usage of WebSphere application server."
  description: "Detected usage of WebSphere application server."

- ruleID: "appserver-glassfish-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=GlassFish"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: org\.glassfish:.*
      - builtin.filecontent:
          filePattern: build.gradle
          pattern: implementation\s*['"]org.glassfish:.*['"]
      - builtin.filecontent:
          filePattern: build.gradle.kts
          pattern: implementation\(['"]org.glassfish:.*['"]\)
  message: "Detected usage of GlassFish application server."
  description: "Detected usage of GlassFish application server."

- ruleID: "appserver-payara-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=Payara"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: fish\.payara\..*:.*
      - builtin.filecontent:
          filePattern: build.gradle
          pattern: implementation\s*['"]fish.payara.*:.*['"]
      - builtin.filecontent:
          filePattern: build.gradle.kts
          pattern: implementation\(['"]fish.payara.*:.*['"]\)
  message: "Detected usage of Payara application server."
  description: "Detected usage of Payara application server."

- ruleID: "appserver-undertow-gradle"
  category: "mandatory"
  effort: 1
  labels:
    - "cto.io/appserver=Undertow"
  when:
    or:
      - builtin.filecontent:
          filePattern: all-deps-nodupes.txt
          pattern: io\.undertow:.*
      - builtin.filecontent:
          filePattern: build.gradle
          pattern: implementation\s*['"]io.undertow:.*['"]
      - builtin.filecontent:
          filePattern: build.gradle.kts
          pattern: implementation\(['"]io.undertow:.*['"]\)
  message: "Detected usage of Undertow application server."
  description: "Detected usage of Undertow application server."
